from tkinter import *

def file_write():
    day = date_text.get()
    file1 = open(day+'.txt','w')
    file1.write(day+"\n")
    file1.write(title_text.get()+"\n")
    file1.write(content_text.get()+"\n")
    date_text.delete(0, END)
    title_text.delete(0, END)
    content_text.delete(0, END)

def file_read():
    day = date_text.get()
    file2=open(day+'.txt','r')
    day_data = file2.readline().strip('\n')
    title_data = file2.readline().strip('\n')
    title_text.insert(0,title_data)
    content_data = file2.readline().strip('\n')
    content_text.insert(0,content_data)

w = Tk()
w.geometry('500x800')

icon = PhotoImage(file='001.png')
img_label = Label(w, image=icon)
img_label.pack()
date_label = Label(w, text='날짜:',font=('궁서',30))
date_text = Entry(w,font=('궁서',30),bg='yellow')
title_label = Label(w, text='제목:',font=('궁서',30))
title_text = Entry(w,font=('궁서',30),bg='yellow')
content_label = Label(w, text='내용:',font=('궁서',30))
content_text = Entry(w,font=('궁서',30),bg='yellow')
date_label.pack()
date_text.pack()
title_label.pack()
title_text.pack()
content_label.pack()
content_text.pack()
write_button = Button(w,text='파일로 저장', command=file_write, font=('궁서',30), bg='lime')
read_button = Button(w,text='파일로 읽기', command=file_read, font=('궁서',30), bg='lime')
write_button.pack()
read_button.pack()
w.mainloop()
